SCCheckinV3/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SCCheckinV3;

namespace SCCheckinV3.Controllers
{
    public class AdminController : Controller
    {
        private SCCheckInEntities db = new SCCheckInEntities();

        // GET: Admin
        public ActionResult Index()
        {
            return View(db.AspNetUsers.ToList());
        }

        // GET: Admin/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            db.AspNetUsers.Remove(aspNetUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SCCheckinV3/Controllers/FeeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SCCheckinV3;

namespace SCCheckinV3.Controllers
{
    public class FeeController : Controller
    {
        private SCCheckInEntities db = new SCCheckInEntities();

        // GET: Fee
        public ActionResult Index()
        {
            return View(db.tblFees.ToList());
        }

        // GET: Fee/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblFee tblFee = db.tblFees.Find(id);
            if (tblFee == null)
            {
                return HttpNotFound();
            }
            return View(tblFee);
        }

        // GET: Fee/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblFee tblFee = db.tblFees.Find(id);
            if (tblFee == null)
            {
                return HttpNotFound();
            }
            return View(tblFee);
        }

        // POST: Fee/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FeeID,FeeCode,FeeAmount")] tblFee tblFee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblFee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblFee);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SCCheckinV3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SCCheckinV3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SCCheckinV3/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SCCheckinV3;

namespace SCCheckinV3.Controllers
{
    public class MemberController : Controller
    {
        private SCCheckInEntities db = new SCCheckInEntities();

        // GET: Member
        public ActionResult Index()
        {
            return View(db.OKSwingMemberLists.ToList());
        }

        // GET: Member/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OKSwingMemberList oKSwingMemberList = db.OKSwingMemberLists.Find(id);
            if (oKSwingMemberList == null)
            {
                return HttpNotFound();
            }
            return View(oKSwingMemberList);
        }

        // GET: Member/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Member/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MemberID,FirstName,MiddleName,LastName,Address,City,State,Zip,HomePhone,WorkPhone,FaxNumber,EmailAddress,Status,DateJoined,Type,LastPaid,Dues,InputDate,MemberStatus,Organization,DOB,Anniversary,DataEaseMemberNumber,BirthMonth,BirthDay,Charter,NewMemberDate,DateLastUpdated,LastUpdatedBy,Dateadded,AddedBy,Comments,CellPhone,InvalidAddress,IsDeleted,ClassID,isPromoted,currentMonth")] OKSwingMemberList oKSwingMemberList)
        {
            if (ModelState.IsValid)
            {
                db.OKSwingMemberLists.Add(oKSwingMemberList);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(oKSwingMemberList);
        }

        // GET: Member/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OKSwingMemberList oKSwingMemberList = db.OKSwingMemberLists.Find(id);
            if (oKSwingMemberList == null)
            {
                return HttpNotFound();
            }
            return View(oKSwingMemberList);
        }

        // POST: Member/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MemberID,FirstName,MiddleName,LastName,Address,City,State,Zip,HomePhone,WorkPhone,FaxNumber,EmailAddress,Status,DateJoined,Type,LastPaid,Dues,InputDate,MemberStatus,Organization,DOB,Anniversary,DataEaseMemberNumber,BirthMonth,BirthDay,Charter,NewMemberDate,DateLastUpdated,LastUpdatedBy,Dateadded,AddedBy,Comments,CellPhone,InvalidAddress,IsDeleted,ClassID,isPromoted,currentMonth")] OKSwingMemberList oKSwingMemberList)
        {
            if (ModelState.IsValid)
            {
                db.Entry(oKSwingMemberList).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(oKSwingMemberList);
        }

        // GET: Member/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OKSwingMemberList oKSwingMemberList = db.OKSwingMemberLists.Find(id);
            if (oKSwingMemberList == null)
            {
                return HttpNotFound();
            }
            return View(oKSwingMemberList);
        }

        // POST: Member/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OKSwingMemberList oKSwingMemberList = db.OKSwingMemberLists.Find(id);
            db.OKSwingMemberLists.Remove(oKSwingMemberList);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SCCheckinV3/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SCCheckinV3;

namespace SCCheckinV3.Controllers
{
    public class SearchController : Controller
    {
        private SCCheckInEntities db = new SCCheckInEntities();

        // GET: Search
        // whoCalled Index
        // 0 (Default) = Add Check In Record
        // 1 = Edit Dancer
        // 2 = Edit Key Tag
        // 3 = Add Key Tag
        public ActionResult Index(int whoCalled = 0)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(int whoCalled, int? memberID)
        {
            switch (whoCalled)
            {
                case 0:
                    break;
                case 1:
                    break;
                case 2:
                    break;
                case 3:
                    break;
                default:
                    break;
            }
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SCCheckinV3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About SCCheckIn Version 3";
}
<h2>@ViewBag.Title.</h2>

<p>Swing Club Check In (SCCheckIn) is a Dancer Management Program Created By Volunteer Programmers At The Oklahoma City Swing Dance Club.</p>
<p>The First Version Was a Microsoft Access Database Ran on a Windows 98 Machine by an Unknown Designer.</p>
<p>The Second Version of SCCheckIn Was Created in VB.NET And a SQL Server Database by Erik Thomson Using 2008 Technologies. David Schrock Took Over The Project in 2011 Creating Versions 2.02 Through 2.09.</p>
<p>The Third Version of SCCheckIn, Created by David Schrock, Is the Latest Version of The Program. It Was Created in ASP.NET MVC Version 5 Using Entity Framework With a SQL Server 2016 Database In The C# Language.</p>

SCCheckinV3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact The Oklahoma City Swing Dance Club";
}
<h2>@ViewBag.Title.</h2>

<address>
    4361 N.W. 50th Suite 400<br />
    Oklahoma City, OK 73112<br />
    <abbr title="Phone">P:</abbr>
    405.943.1950
</address>

<address>
    <strong>Marketing and Information:</strong> <a href="mailto:swingdanceokc@gmail.com">Email The Club</a>
</address>

SCCheckinV3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h2>Welcome to Swing Club Check In Version 3</h2>
    @if (!User.Identity.IsAuthenticated)
    {
        <h3>Please @Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" }) To The System.</h3>
    }
    else
    {
        <h3>Please Select a Function Below.</h3>
    }
</div>

@if (User.Identity.IsAuthenticated)
{
    <div class="row">
        <div class="col-md-4">
            <h3>Check In Functions</h3>
            @Html.ActionLink("Add a Check In Record","Index","Search")<br />
            @Html.ActionLink("Create New Dancer", "Create", "Member")<br />
        </div>
        <div class="col-md-4">
            <h3>Reports</h3>
            @Html.ActionLink("Monthly Dancers","MonthlyDancers","Report")<br />
            @Html.ActionLink("Dancers Currently In Lessons", "DancersCurrentlyInLessons", "Report")<br />
            @Html.ActionLink("Todays Dancers", "TodaysDancers", "Report")<br />
            @Html.ActionLink("Todays Paying Dancers","TodaysPayingDancers","Report")<br />
            @Html.ActionLink("Todays Summary","TodaysSummary","Report")<br />
            @Html.ActionLink("Yearly Dues","YearlyDues","Report")<br />
            @Html.ActionLink("Year Over Year Sales","YearOverYearSales","Report")<br />
            @Html.ActionLink("Email List", "EmailList", "Report")<br />
            @Html.ActionLink("Special Events","SpecialEvents","Report")<br />
            @Html.ActionLink("Unknown Dancers", "UnknownDancers","Report")<br />
            @Html.ActionLink("Pink Dancers", "PinkDancers","Report")<br />
            @Html.ActionLink("Purple Dancers", "PurpleDancers","Report")<br />
            @Html.ActionLink("Yellow Dancers", "YellowDancers", "Report")<br />
            @Html.ActionLink("Green Dancers", "GreenDancers", "Report")<br />
            @Html.ActionLink("Blue Dancers","BlueDancers","Report")<br />
            @Html.ActionLink("Teachers","Teachers","Report")<br />
            @Html.ActionLink("Birthdays","Birthdays","Report")<br />
            @Html.ActionLink("Members Modified In Database","MembersModifiedInDatabase","Report")<br />
            @Html.ActionLink("Non Returning Members","NonReturningMembers","Report")<br />
            @Html.ActionLink("Missing In Action","MissingInAction","Report")<br />
            @Html.ActionLink("Expiring Members","ExpiringMembers","Report")<br />
            @Html.ActionLink("New Dancers","NewDancers","Report")<br />
            @Html.ActionLink("New Members","NewMembers","Report")<br />
            @Html.ActionLink("Renewing Members","RenewingMembers","Report")<br />
            @Html.ActionLink("Voided Entries", "Voided Entries","Report")<br />
            @Html.ActionLink("Deleted Members","DeletedMembers","Report")<br />
            @Html.ActionLink("Currently Paid Members","CurrentlyPaidMembers","Report")<br />
            @Html.ActionLink("Complete Member List","CompleteMemberList","Report")<br />
            @Html.ActionLink("Three Year Sales Data", "ThreeYearSales", "Report")<br />
        </div>
        <div class="col-md-4">
            <h3>Administrative Functions</h3>
            @Html.ActionLink("Edit Dancer Information","Index","Search", new { whoCalled = 1 }, null)<br />
            @Html.ActionLink("Add a Key Tag", "Index", "Search", new { whoCalled = 3 }, null)<br />
            @Html.ActionLink("Edit Key Tag", "Index", "Search", new { whoCalled = 2 }, null)<br />
            @Html.ActionLink("Edit Merchandise","Index","Merchandise")<br />
            @Html.ActionLink("Edit Club Fees", "Index", "Fee")<br />
            @Html.ActionLink("Remove Administrators", "Index", "Admin")<br />
        </div>
    </div>
}